export const ErrorCode = {
  // Auth errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_EXISTS: "USER_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  NO_TOKEN: "NO_TOKEN",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // Permission errors
  FORBIDDEN: "FORBIDDEN",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // General errors
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  CONFLICT: "CONFLICT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];